"""Add assignment_status to Patient model

Generated by the assistant. Run migrations to apply.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
    ]
