# Generated by Django 5.2.10 on 2026-01-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_appointment_status_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
