# Generated by Django 5.2.10 on 2026-01-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_appointment_zoom_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
