# Generated by Django 5.2.10 on 2026-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_appointment_zoom_start_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='zoom_join_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zoom_start_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
